### ISSUE TITLE
Convert BTC

### ISSUE THREAD

**Issue by uitlaber** [responsiv/currency-plugin#17]
I need convert from USD to BTC and return 0.00 :( Ho to change round?

**Comment by daftspunk** [comment]
Try this

    Currency::format($fiatAmount, [
            'from' => 'USD',
            'to' => 'BCH',
            'decimals' => 8
        ]);

**Comment by uitlaber** [comment]
not work for me.
I try hardcode 
` public function convert($value, $fromCurrency, $toCurrency, $round = 8)`
in plugins\responsiv\currency\classes\Converter.php  
not work

**Comment by daftspunk** [comment]
Seems to work here. Can you give complete replication instructions. Is it configured to use CoinMarketCap?

**Comment by uitlaber** [comment]
I tried format 1 USD to BTC :)

**Comment by daftspunk** [comment]
Go to Settings to make sure you have CoinMarketCap selected, its needed for crypto conversions.

**Comment by uitlaber** [comment]
Sorry, in http://octobercms.com  not last version this plugin.
