### ISSUE TITLE
Update plugin at octobercms.com

### ISSUE THREAD

**Issue by kEERill** [responsiv/currency-plugin#18]
On the site of OctoberCMS old version of the plugin

**Comment by alxy** [comment]
@daftspunk Push, you should probably use the automatic pull/build option for these plugins...

**Comment by alxy** [comment]
@daftspunk Another push, it is really annoying to update the plugins manually, when there are certain issues already fixed. This plugin is on 1.0.2 on the marketplace: http://octobercms.com/plugin/responsiv-currency

**Comment by daftspunk** [comment]
Done
