### ISSUE TITLE
How to use format from and to currency in twig.

### ISSUE THREAD

**Issue by worldofsmarty** [responsiv/currency-plugin#24]
How to use : Currency::format(10, ['from' => 'USD', 'to' => 'BTC']); in Twig

**Comment by lesz3u** [comment]
> How to use : Currency::format(10, ['from' => 'USD', 'to' => 'BTC']); in Twig

It's probably too late but:

{{ 10 | currency({ from: 'USD', to: 'BTC' }) }}
