### ISSUE TITLE
Error after last update

### ISSUE THREAD

**Issue by exaline-ru** [responsiv/currency-plugin#28]
![image](https://user-images.githubusercontent.com/46493161/70387773-60fc9980-19ba-11ea-89ab-1a71d93b80fe.png)

**Comment by daftspunk** [comment]
This should be fixed by https://github.com/responsiv/currency-plugin/commit/9264f0a1f6359cefb8237eacb251bf4bcd06ceda

Apologies for the error, you can manually update this file to add the missing comma and the build should be fixed for future instances
