### ISSUE TITLE
Target class [responsiv.currency.helper] does not exist.

### ISSUE THREAD

**Issue by PaavaliPoika** [responsiv/currency-plugin#41]
Can anyone come across this? Caught a error on Winter 1.2.3 (Laravel 9)
**An exception has been thrown during the rendering of a template ("Target class [responsiv.currency.helper] does not exist.").**

` {% if item.is_price %}
    <div class="col-xl-6 col-lg-6">
        <p class="gradient-8 mt30 mb30 pt10 pb10 text-center white-color rounded">
            <strong>{{ item.price | currency ({ from: 'USD', to: 'EUR' }) }}</strong>
       </p>
    </div>
{% endif %}`

What am I doing wrong?

**Comment by daftspunk** [comment]
I doubt it. Try using October CMS.
