### ISSUE TITLE
Can't change Euro valuta formatting

### ISSUE THREAD

**Issue by kevin-invato** [responsiv/currency-plugin#45]
Hi there,

I was testing the new update (looks very nice!) but I can't change the euro valuta, I get the following message:

`"Responsiv\Currency\Models\Currency::fromBaseValue(): Return value must be of type float, string returned" on line 184 of /.........../plugins/responsiv/currency/models/Currency.php`

The default euro formatting isn't correct, so I wanted to change it to the correct format:
€1.234,56 (thousand separator as a dot and decimal separator a comma)

Hopefully you can fix this (or change the default euro formatting).

Thanks in advance!

- Kevin

**Comment by daftspunk** [comment]
Hey @kevin-invato 

Thanks for finding this, we have released a new patch that should fix it (v2.0.5).

**Comment by kevin-invato** [comment]
@daftspunk  Works perfectly now, thanks!
