### ISSUE TITLE
More configurable behaviour (for back compatibility)

### ISSUE THREAD

**Issue by snipiba** [responsiv/currency-plugin#46]
As a long term data usage, there must be more configurable things to avoid missleading conversions based on "base value".

Example:
before we had number field, where client put a real number, for example 25 as representation of 25,00 Eur.
now, new plugin display this value as 0,25 what is missleading, then type: currency may contain baseValue: true|false to avoid this conversion without any previous "consent" :)

Update of this plugin currently broke whole system, because currency formatting is missleading, then paypal provider, stripe provider are not able to process correct values, what means, this is really big big mistake, 
to consider that everything is wrote down in thousands, to get a correct base value.

And.. of course... 
Partial to show formfield shows price format as `baseValue => false` and saving is procceeded with toBaseValue($value) ... this is confusing as well. when, input field is formatted as baseValue false, that means, when user put 25 inside as corrected value, then base is saved as 2500..

Whole thing is soooooo messy guys. List column shows field as base value false too, then there is multiple missleading informations and now im not able to decide, what is correct way how to handle whole thing, because, when i multiply current prices, old saved orders will show wrong values like 0,85 instead of 85, etc...

**Comment by daftspunk** [comment]
Hi @snipiba 

It helps to look at the upgrade guide: https://github.com/responsiv/currency-plugin/blob/master/UPGRADE.md

This change is necessary to overcome common rounding errors and ensure future proofing for alternative currencies that may have up to 8 decimal places (1.23456789).

I hope this helps!

**Comment by snipiba** [comment]
i know what struggle is to create a options, to allows users decide if they want to use "cents" or "dollars" or what kind of "metric" we will call it... but i think out loud, that "strict" policy is lil bit aggressive. for example, paypal and stripe are not using same metrics as well. :) that is a one of problem what i dealt with after update october and plugins... just everything goes to hell.

i read that upgrade.md and multiplied values, but as i mentoined on discord, there are plenty of relations based on orders, related to baskets, invoices, etc etc, where is "historical" data stored as json, then i wont "reparse" that and "recalculate" because of one decission... u know. 

just a lil bit dissapointed after all that gr8 job u guys have done, this was... disaster.

**Comment by daftspunk** [comment]
I am sorry that this is a significant upgrade and may involve a lot of work for you to attend to. Unfortunately, [this is the way the world is headed](https://www.moneyphp.org/en/stable/features/operation.html) due to the intrinsic flaws found in decmals/floats and the future-proofing of fractional currencies.
