### ISSUE TITLE
How to use the format option in the twig ?

### ISSUE THREAD

**Issue by chrisvidal** [responsiv/currency-plugin#8]
How to use the format short to display this value in a twig template ?
````{ 10|currency }}````

**Comment by chrisvidal** [comment]
damn, so easy, i found the solution

````10|currency({ format: 'short' })````

**Comment by pjjk** [comment]
As should {{ 1|currency({ to: 'USD' }) }} - thanks for the hint @chrisvidal
Pretty poor docs. from: doesn't seem to work, but that is not a disaster

**Comment by pjjk** [comment]
'from' needs to have 'to' explicit {{ 1|currency({ from: 'EUR',to: 'AUD'}) }}
