### ISSUE TITLE
Call to undefined method October\Rain\Support\Singleton::listConverters()

### ISSUE THREAD

**Issue by joseph-d** [responsiv/currency-plugin#9]
With a clean install of OctoberCMS, I have installed this plugin. 

Under settings, "Currencies" shows a list of some currencies.

However, clicking on "Currency converters" in the settings throws an exception:

```
Call to undefined method October\Rain\Support\Singleton::listConverters()

/var/www/project/plugins/responsiv/currency/models/ExchangeConverter.php line 73

TYPE

Undefined

EXCEPTION

Symfony\Component\Debug\Exception\FatalErrorException
```

**Comment by daftspunk** [comment]
I've seen this too, only on some PHP versions. Which do you use?

**Comment by joseph-d** [comment]
My php -v output is:

```
PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

And, yes, you're right, I just tried it on another machine with PHP 7.0.8 and the problem doesn't occur.

**Comment by daftspunk** [comment]
Unfortunately I think it is a bug in PHP 5.5.9. We'll need to implement a fix in the library. I'll leave this open as a reference for replicating the bug.

**Comment by daftspunk** [comment]
October now uses PHP 7 so it shouldn't happen anymore!
